# Generated by Django 5.2.8 on 2025-11-22 05:30

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('current_position', models.CharField(blank=True, max_length=200, null=True)),
                ('current_company', models.CharField(blank=True, max_length=200, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('high-school', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=50, null=True)),
                ('preferred_locations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('preferred_salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidate_profiles',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(help_text='Path in MinIO storage', max_length=500)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type (e.g., application/pdf)', max_length=50)),
                ('parsed_data', models.JSONField(blank=True, default=dict, help_text='Structured data from resume parser')),
                ('raw_text', models.TextField(blank=True, help_text='Extracted raw text', null=True)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('education', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('certifications', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='Sentence-BERT embedding', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resumes',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['candidate', 'is_active'], name='resumes_candida_e17708_idx')],
            },
        ),
    ]
